#!/usr/bin/env node
// Headless DeepSeek runner for the TurdMOD research/extraction team.
// Opus (parent) drives this to offload bulk RE/mapping reasoning cheaply;
// it reviews + applies the output. NOT a source of ground truth — DeepSeek
// has no access to the binary, so its RE output is a HYPOTHESIS dossier to
// validate against the runtime engine_resolve probe.
//
// Usage:
//   node tools/deepseek/run.mjs --in <prompt.md> --out <result.md> \
//        [--model deepseek-reasoner|deepseek-chat] [--system <system.md>] \
//        [--max 8000]
//
// Env: DEEPSEEK_API_KEY (required).
// @dep: api.deepseek.com/chat/completions (OpenAI-compatible)
import { readFileSync, writeFileSync } from 'node:fs';

function arg(name, def) {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 && process.argv[i + 1] ? process.argv[i + 1] : def;
}

const key = process.env.DEEPSEEK_API_KEY;
if (!key) { console.error('DEEPSEEK_API_KEY not set'); process.exit(2); }

const inPath = arg('in');
const outPath = arg('out');
const model = arg('model', 'deepseek-chat');
const sysPath = arg('system');
const maxTokens = parseInt(arg('max', '8000'), 10);
if (!inPath || !outPath) { console.error('need --in and --out'); process.exit(2); }

const system = sysPath
  ? readFileSync(sysPath, 'utf8')
  : [
    'You are a senior reverse-engineer and UE4.27 internals expert on the TurdMOD research team.',
    'CONTRACT (anti-confabulation — this matters more than completeness):',
    '1. You have NO access to the target binary, the class dump, or the live engine — ONLY what is',
    '   pasted into this prompt is ground truth. Anything else is your inference.',
    '2. Do NOT invent a real function name, class name, offset, or signature. If a fact you need is',
    '   not provided here, output `NEEDS-DATA: <exactly what to fetch and the RPC/command to get it>`',
    '   instead of a plausible guess. A confident wrong name is worse than an honest gap — it ships bugs.',
    '3. Tag every concrete symbol you name: `[FACT: from prompt]` for given truths, `[INFER]` for your',
    '   reasoning. Frame any offset/index/vtable position as a candidate to validate against the live probe.',
    '4. Prefer structured, checkable claims (Class.Field @offset, fn on Owner(params)) over loose prose.',
    '5. END your output with a `## CLAIMS` section — one machine-verifiable line per concrete engine claim',
    '   you made: `- <type>: <subject> [FACT|INFER]`, type in fn|field|class|handler|event|behavior',
    '   (field as Class.Field @offset; class as Name extends Parent). List EVERY engine symbol you named —',
    '   a claim omitted from this block is a claim you are hiding. It is auto-verified against the dump + engine.',
    'Output clean GitHub-flavored Markdown.',
  ].join('\n');
const user = readFileSync(inPath, 'utf8');

const body = {
  model,
  messages: [
    { role: 'system', content: system },
    { role: 'user', content: user },
  ],
  temperature: 0.2,
  max_tokens: maxTokens,
};

const t0 = Date.now();
const res = await fetch('https://api.deepseek.com/chat/completions', {
  method: 'POST',
  headers: { 'content-type': 'application/json', authorization: `Bearer ${key}` },
  body: JSON.stringify(body),
});
if (!res.ok) {
  console.error(`deepseek HTTP ${res.status}: ${(await res.text()).slice(0, 500)}`);
  process.exit(1);
}
const json = await res.json();
const msg = json.choices?.[0]?.message ?? {};
const content = msg.content ?? '';
const reasoning = msg.reasoning_content ?? '';
const usage = json.usage ?? {};
const elapsed = ((Date.now() - t0) / 1000).toFixed(1);

const header = `<!-- generated by tools/deepseek/run.mjs · model=${model} · ${elapsed}s · ` +
  `tokens in/out=${usage.prompt_tokens ?? '?'}/${usage.completion_tokens ?? '?'} -->\n` +
  `<!-- HYPOTHESIS DOSSIER — DeepSeek has no binary access. Validate every concrete ` +
  `pointer/offset/index against the runtime engine_resolve probe before trusting it. -->\n\n`;

let footer = '';
if (reasoning) {
  footer = `\n\n---\n<details><summary>model reasoning trace (debug)</summary>\n\n` +
    '```\n' + reasoning.slice(0, 6000) + '\n```\n</details>\n';
}

writeFileSync(outPath, header + content + footer, 'utf8');
console.error(`wrote ${outPath} (${content.length} chars, ${elapsed}s, ` +
  `${usage.completion_tokens ?? '?'} out-tokens)`);
