packages:
  - "apps/turdmod-cli"
  - "apps/turdmod-registry"
  - "apps/turdmod-companion"
  - "apps/turdmod-guard/backend"
  - "apps/turdmod-web"
  - "apps/turdmod-manager"
  - "apps/turdmod-launcher"
  - "apps/turdmod-lite"
  - "apps/turdmod-pro"
  - "apps/turdmod-bot"
  - "apps/turdmod-creator"
  - "examples/turdmod/*"
  - "mods/*"
  - "packages/*"
